/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab5_arielreyes;

import java.util.ArrayList;
import java.util.Random;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Ariel
 */
public class Main extends javax.swing.JFrame {
Random ale = new Random(); 

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        // ingenuiera
        DefaultComboBoxModel siste = (DefaultComboBoxModel) cb_sistemas.getModel();
        siste.addElement(new ing_sistemas("Sistemas computacionales", "Ingeneria", "Sistemas", (float) 1000.3, "Bocanegra"));
        siste.addElement(new ing_sistemas("Industrial y de sistemas", "Ingeneria", "Facultad de industrial", (float) 1240.3, "Mario Eduardo"));
        siste.addElement(new ing_sistemas("Biomedica y Energia ", "Ingeneria", "Facultad de Energia", (float) 3240.3, " Jose Lopez"));
        cb_sistemas.setModel(siste);
        // Licenciatura
        DefaultComboBoxModel lice = (DefaultComboBoxModel) cb_licenciatura.getModel();
        lice.addElement(new Licencuatura("Finanzas", "Licenciatura", "Facultad de Finanzas y Economia", (float) 34444.3, "Alejandra Chavez"));
        lice.addElement(new Licencuatura("Derecho", "Licenciatura", "Facultad de Derecho", (float) 344.3, "Julio Chavez"));
        lice.addElement(new Licencuatura("Administracion de empresas", "Licenciatura", "Facultad de Desarrollo", (float) 34433.3, "Carlos Cano"));
        lice.addElement(new Licencuatura("Diseño", "Licenciatura", "Facultad de desarrollo grafico", (float) 5000.3, "Lupe Cano"));
        lice.addElement(new Licencuatura("Mecatronica", "Licenciatura", "Facultad de Sistemas", (float) 50300.3, "Maria Noca"));
        cb_licenciatura.setModel(lice);
        // ciencias de salud 
        DefaultComboBoxModel ciencia = (DefaultComboBoxModel) cb_ciencias_salud.getModel();
        ciencia.addElement(new ciencias_salud("Medicina y cirugia ", "Ciencias de salud", "Medicina", (float) 9000.2, "Esteban Martinez"));
        ciencia.addElement(new ciencias_salud("Odontologia ", "Ciencias de salud", "Medicina", (float) 9000.2, "Esteban Martinez"));
        ciencia.addElement(new ciencias_salud("Nutricion y terapia fisica ", "Ciencias de salud", "Medicina", (float) 9300.2, "Lucia Montes"));
        ciencia.addElement(new ciencias_salud("Opcional", "Ciencias de salud", "Medicina", (float) 9300.2, "Esteban Martinez"));
        cb_ciencias_salud.setModel(ciencia);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        estudian = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jt_estudiantes = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_apellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        sp_edad = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        rd_sistema = new javax.swing.JRadioButton();
        rd_licenciatura = new javax.swing.JRadioButton();
        rd_cienca_salud = new javax.swing.JRadioButton();
        cb_sistemas = new javax.swing.JComboBox<>();
        cb_licenciatura = new javax.swing.JComboBox<>();
        cb_ciencias_salud = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_estudiantes = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        rb_hombre = new javax.swing.JRadioButton();
        rd_mujer = new javax.swing.JRadioButton();
        sexos = new javax.swing.ButtonGroup();
        carreras = new javax.swing.ButtonGroup();
        Eliminar_modificar = new javax.swing.JPopupMenu();
        Eliminar = new javax.swing.JMenuItem();
        Modificar = new javax.swing.JMenuItem();
        Carreras = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jTextField3 = new javax.swing.JTextField();
        rd_ing = new javax.swing.JRadioButton();
        rd_lic = new javax.swing.JRadioButton();
        rd_ciencia = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        Clases = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        aire = new javax.swing.ButtonGroup();
        Maestro = new javax.swing.JDialog();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        jButton5 = new javax.swing.JButton();
        cb_class = new javax.swing.JComboBox<>();
        lista_maestro_clase = new javax.swing.JDialog();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_maestro_clases = new javax.swing.JList<>();
        menu_lista_maestro_clases = new javax.swing.JPopupMenu();
        Delete = new javax.swing.JMenuItem();
        Mod = new javax.swing.JMenuItem();
        Mod_clases = new javax.swing.JMenuItem();
        Modificar_clases = new javax.swing.JDialog();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jFormattedTextField5 = new javax.swing.JFormattedTextField();
        jLabel28 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        Modificar_Maestro = new javax.swing.JDialog();
        jLabel31 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jFormattedTextField6 = new javax.swing.JFormattedTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jFormattedTextField7 = new javax.swing.JFormattedTextField();
        jLabel37 = new javax.swing.JLabel();
        cb_class1 = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        jLabel1.setText("Nombre: ");

        jLabel2.setText("Apellido: ");

        jLabel4.setText("Edad: ");

        sp_edad.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel5.setText("Sexo: ");

        carreras.add(rd_sistema);
        rd_sistema.setText("Sistemas");
        rd_sistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_sistemaActionPerformed(evt);
            }
        });

        carreras.add(rd_licenciatura);
        rd_licenciatura.setText("Licenciatura");
        rd_licenciatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_licenciaturaActionPerformed(evt);
            }
        });

        carreras.add(rd_cienca_salud);
        rd_cienca_salud.setText("Ciencias de salud");
        rd_cienca_salud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_cienca_saludActionPerformed(evt);
            }
        });

        cb_sistemas.setEnabled(false);
        cb_sistemas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_sistemasActionPerformed(evt);
            }
        });

        cb_licenciatura.setEnabled(false);

        cb_ciencias_salud.setEnabled(false);

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jl_estudiantes.setModel(new DefaultListModel());
        jl_estudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jl_estudiantesMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jl_estudiantes);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("estudiantes");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTree1MousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTree1);

        sexos.add(rb_hombre);
        rb_hombre.setText("Hombre");

        sexos.add(rd_mujer);
        rd_mujer.setText("Mujer");

        javax.swing.GroupLayout estudianLayout = new javax.swing.GroupLayout(estudian.getContentPane());
        estudian.getContentPane().setLayout(estudianLayout);
        estudianLayout.setHorizontalGroup(
            estudianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(estudianLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(estudianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(estudianLayout.createSequentialGroup()
                        .addGroup(estudianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(43, 43, 43)
                        .addGroup(estudianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jt_estudiantes, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_apellido, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sp_edad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(rb_hombre, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(estudianLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(estudianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_sistemas, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(estudianLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(rd_sistema)
                .addGap(61, 61, 61)
                .addGroup(estudianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(estudianLayout.createSequentialGroup()
                        .addGroup(estudianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(estudianLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jButton1))
                            .addGroup(estudianLayout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rd_mujer))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(estudianLayout.createSequentialGroup()
                        .addComponent(cb_licenciatura, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(cb_ciencias_salud, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))
                    .addGroup(estudianLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(rd_licenciatura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rd_cienca_salud)
                        .addGap(102, 102, 102))))
        );
        estudianLayout.setVerticalGroup(
            estudianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(estudianLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(estudianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jt_estudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(estudianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(estudianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sp_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(estudianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rb_hombre)
                    .addComponent(rd_mujer))
                .addGap(35, 35, 35)
                .addGroup(estudianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rd_sistema)
                    .addComponent(rd_licenciatura)
                    .addComponent(rd_cienca_salud))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(estudianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_sistemas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_licenciatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_ciencias_salud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(estudianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        Eliminar_modificar.add(Eliminar);

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        Eliminar_modificar.add(Modificar);

        jLabel3.setText("Carreras");

        jLabel6.setText("Nombre: ");

        jLabel7.setText("Facultad: ");

        jLabel8.setText("Costo mensual:  ");

        jLabel9.setText("Jefe carrera: ");

        carreras.add(rd_ing);
        rd_ing.setText("Ingenieria ");

        carreras.add(rd_lic);
        rd_lic.setText("Licenciatura");

        carreras.add(rd_ciencia);
        rd_ciencia.setText("Ciencias de la salud");
        rd_ciencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_cienciaActionPerformed(evt);
            }
        });

        jLabel11.setText("Nombre de la carrera: ");

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CarrerasLayout = new javax.swing.GroupLayout(Carreras.getContentPane());
        Carreras.getContentPane().setLayout(CarrerasLayout);
        CarrerasLayout.setHorizontalGroup(
            CarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CarrerasLayout.createSequentialGroup()
                .addGroup(CarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CarrerasLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(CarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(CarrerasLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextField1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CarrerasLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField2))
                            .addGroup(CarrerasLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(CarrerasLayout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(jLabel3))
                    .addGroup(CarrerasLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CarrerasLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(CarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(rd_ing))
                        .addGroup(CarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CarrerasLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CarrerasLayout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addGroup(CarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton2)
                                    .addComponent(rd_lic))
                                .addGap(59, 59, 59)
                                .addComponent(rd_ciencia)))))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        CarrerasLayout.setVerticalGroup(
            CarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CarrerasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(50, 50, 50)
                .addGroup(CarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(CarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(CarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(CarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(CarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rd_ing)
                    .addComponent(rd_lic)
                    .addComponent(rd_ciencia))
                .addGap(31, 31, 31)
                .addComponent(jButton2)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jLabel10.setText("jLabel10");

        jLabel12.setText("Crear clase ");

        jLabel13.setText("Nombre: ");

        jLabel14.setText("Seccion: ");

        jLabel15.setText("Edificacion: ");

        jLabel16.setText("Salon: ");

        jLabel17.setText("Aire acondicionado: ");

        aire.add(jRadioButton1);
        jRadioButton1.setText("SI");

        aire.add(jRadioButton2);
        jRadioButton2.setText("No");

        jButton3.setText("Crear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ClasesLayout = new javax.swing.GroupLayout(Clases.getContentPane());
        Clases.getContentPane().setLayout(ClasesLayout);
        ClasesLayout.setHorizontalGroup(
            ClasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClasesLayout.createSequentialGroup()
                .addGroup(ClasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ClasesLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(ClasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ClasesLayout.createSequentialGroup()
                                .addGroup(ClasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14))
                                .addGap(18, 18, 18)
                                .addGroup(ClasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(ClasesLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel17)
                            .addGroup(ClasesLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(ClasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ClasesLayout.createSequentialGroup()
                            .addGap(123, 123, 123)
                            .addComponent(jRadioButton1)
                            .addGap(85, 85, 85)
                            .addComponent(jRadioButton2))
                        .addGroup(ClasesLayout.createSequentialGroup()
                            .addGap(255, 255, 255)
                            .addComponent(jLabel12)))
                    .addGroup(ClasesLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(353, Short.MAX_VALUE))
        );
        ClasesLayout.setVerticalGroup(
            ClasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClasesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(43, 43, 43)
                .addGroup(ClasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(ClasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(ClasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(ClasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addGroup(ClasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        jLabel18.setText("Maestros ");

        jLabel19.setText("Nombre: ");

        jLabel20.setText("Apellido: ");

        jLabel21.setText("Salario: ");

        jLabel22.setText("Edad: ");

        jLabel23.setText("Clases");

        jButton5.setText("Agregar Maestro");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MaestroLayout = new javax.swing.GroupLayout(Maestro.getContentPane());
        Maestro.getContentPane().setLayout(MaestroLayout);
        MaestroLayout.setHorizontalGroup(
            MaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MaestroLayout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(jLabel18)
                .addContainerGap(320, Short.MAX_VALUE))
            .addGroup(MaestroLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(MaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel21)
                        .addGroup(MaestroLayout.createSequentialGroup()
                            .addGroup(MaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(MaestroLayout.createSequentialGroup()
                                    .addGroup(MaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel20)
                                        .addComponent(jLabel19))
                                    .addGap(38, 38, 38))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MaestroLayout.createSequentialGroup()
                                    .addComponent(jLabel22)
                                    .addGap(43, 43, 43)))
                            .addGroup(MaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jFormattedTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                .addComponent(jFormattedTextField3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextField8)
                                .addComponent(jTextField9)))
                        .addGroup(MaestroLayout.createSequentialGroup()
                            .addComponent(jLabel23)
                            .addGap(38, 38, 38)
                            .addComponent(cb_class, 0, 124, Short.MAX_VALUE)))
                    .addComponent(jButton5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MaestroLayout.setVerticalGroup(
            MaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MaestroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MaestroLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(40, 40, 40)
                        .addGroup(MaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(MaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(jLabel21))
                    .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(MaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jFormattedTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(cb_class, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jButton5)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        jLabel24.setText("Listar Maestros Clases");

        jl_maestro_clases.setModel(new DefaultListModel());
        jl_maestro_clases.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_maestro_clasesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jl_maestro_clases);

        javax.swing.GroupLayout lista_maestro_claseLayout = new javax.swing.GroupLayout(lista_maestro_clase.getContentPane());
        lista_maestro_clase.getContentPane().setLayout(lista_maestro_claseLayout);
        lista_maestro_claseLayout.setHorizontalGroup(
            lista_maestro_claseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lista_maestro_claseLayout.createSequentialGroup()
                .addGroup(lista_maestro_claseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lista_maestro_claseLayout.createSequentialGroup()
                        .addGap(324, 324, 324)
                        .addComponent(jLabel24))
                    .addGroup(lista_maestro_claseLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        lista_maestro_claseLayout.setVerticalGroup(
            lista_maestro_claseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lista_maestro_claseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addGap(59, 59, 59)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        Delete.setText("Eliminar");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        menu_lista_maestro_clases.add(Delete);

        Mod.setText("Modificar_Maestro");
        Mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModActionPerformed(evt);
            }
        });
        menu_lista_maestro_clases.add(Mod);

        Mod_clases.setText("Modificar_clases");
        Mod_clases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mod_clasesActionPerformed(evt);
            }
        });
        menu_lista_maestro_clases.add(Mod_clases);

        jLabel25.setText("Modificar clase ");

        jLabel26.setText("Nombre: ");

        jLabel27.setText("Seccion: ");

        jLabel28.setText("Edificacion: ");

        jLabel29.setText("Salon: ");

        jLabel30.setText("Aire acondicionado: ");

        aire.add(jRadioButton3);
        jRadioButton3.setText("SI");

        aire.add(jRadioButton4);
        jRadioButton4.setText("No");

        jButton4.setText("Modificar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Modificar_clasesLayout = new javax.swing.GroupLayout(Modificar_clases.getContentPane());
        Modificar_clases.getContentPane().setLayout(Modificar_clasesLayout);
        Modificar_clasesLayout.setHorizontalGroup(
            Modificar_clasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Modificar_clasesLayout.createSequentialGroup()
                .addGroup(Modificar_clasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Modificar_clasesLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel25))
                    .addGroup(Modificar_clasesLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(Modificar_clasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Modificar_clasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel27)
                                .addComponent(jLabel26))
                            .addGroup(Modificar_clasesLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(Modificar_clasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel28))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Modificar_clasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField10, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(jFormattedTextField5)
                            .addComponent(jTextField11)
                            .addComponent(jTextField12)))
                    .addGroup(Modificar_clasesLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel30))
                    .addGroup(Modificar_clasesLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jRadioButton3)
                        .addGap(61, 61, 61)
                        .addComponent(jRadioButton4))
                    .addGroup(Modificar_clasesLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jButton4)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        Modificar_clasesLayout.setVerticalGroup(
            Modificar_clasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Modificar_clasesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addGap(41, 41, 41)
                .addGroup(Modificar_clasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(Modificar_clasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jFormattedTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(Modificar_clasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Modificar_clasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jLabel30)
                .addGap(26, 26, 26)
                .addGroup(Modificar_clasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jLabel31.setText("Modificar Maestro ");

        jLabel33.setText("Apellido: ");

        jLabel34.setText("Nombre: ");

        jLabel32.setText("Salario: ");

        jLabel35.setText("Edad: ");

        jLabel36.setText("Edad: ");

        jLabel37.setText("Clases");

        jButton6.setText("Modificar Maestro");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Modificar_MaestroLayout = new javax.swing.GroupLayout(Modificar_Maestro.getContentPane());
        Modificar_Maestro.getContentPane().setLayout(Modificar_MaestroLayout);
        Modificar_MaestroLayout.setHorizontalGroup(
            Modificar_MaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Modificar_MaestroLayout.createSequentialGroup()
                .addGroup(Modificar_MaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Modificar_MaestroLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel31))
                    .addGroup(Modificar_MaestroLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(Modificar_MaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel33)
                            .addComponent(jLabel34)
                            .addComponent(jLabel32)
                            .addComponent(jLabel36)
                            .addComponent(jLabel37))
                        .addGap(18, 18, 18)
                        .addGroup(Modificar_MaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField13)
                            .addComponent(jTextField14)
                            .addComponent(jFormattedTextField6)
                            .addComponent(jFormattedTextField7)
                            .addComponent(cb_class1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(201, Short.MAX_VALUE))
            .addGroup(Modificar_MaestroLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Modificar_MaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Modificar_MaestroLayout.createSequentialGroup()
                    .addGap(208, 208, 208)
                    .addComponent(jLabel35)
                    .addContainerGap(209, Short.MAX_VALUE)))
        );
        Modificar_MaestroLayout.setVerticalGroup(
            Modificar_MaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Modificar_MaestroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31)
                .addGap(53, 53, 53)
                .addGroup(Modificar_MaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addGap(42, 42, 42)
                .addGroup(Modificar_MaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(Modificar_MaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jFormattedTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(Modificar_MaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jFormattedTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(Modificar_MaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(cb_class1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jButton6)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(Modificar_MaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Modificar_MaestroLayout.createSequentialGroup()
                    .addGap(206, 206, 206)
                    .addComponent(jLabel35)
                    .addContainerGap(206, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu3.setText("Menu");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Alumnos");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Agregar carrera");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem3.setText("Crear clase ");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Agregar Maestro");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem5.setText("Lista Maestro y Clases");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 645, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuItem1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        estudiante();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void rd_sistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_sistemaActionPerformed
        // TODO add your handling code here:
         if (rd_sistema.isSelected()) {
                cb_sistemas.setEnabled(true);
                
            }
    }//GEN-LAST:event_rd_sistemaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            String nombre = jt_estudiantes.getText();
            String apellido = tf_apellido.getText();
            int edad = (int) sp_edad.getValue();
            int num_cuenta = 34 + ale.nextInt(10000); 

            String sexo = "";
            if (rb_hombre.isSelected()) {
                sexo = "Hombre";
            } else {
                sexo = "Mujer";

            }

            carrera carre = null;
            if (rd_sistema.isSelected()) {
                carre = (carrera) cb_sistemas.getSelectedItem();
            }
            if (rd_licenciatura.isSelected()) {
                carre = (carrera) cb_licenciatura.getSelectedItem();
            }
            if (rd_cienca_salud.isSelected()) {
                carre = (carrera) cb_ciencias_salud.getSelectedItem();
            }

            estudiantes alumno = new estudiantes(nombre, apellido, num_cuenta, edad, sexo, carre);
            DefaultListModel model = (DefaultListModel) jl_estudiantes.getModel();
            model.addElement(new estudiantes(nombre, apellido, num_cuenta, edad, sexo, carre));
            jl_estudiantes.setModel(model);
            JOptionPane.showMessageDialog(this, "Correcto");
            jt_estudiantes.setText("");
            tf_apellido.setText("");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rd_licenciaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_licenciaturaActionPerformed
        // TODO add your handling code here:
        if (rd_licenciatura.isSelected()) {
            cb_licenciatura.setEnabled(true);

        }
    }//GEN-LAST:event_rd_licenciaturaActionPerformed

    private void rd_cienca_saludActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_cienca_saludActionPerformed
        // TODO add your handling code here:
        if (rd_cienca_salud.isSelected()) {
            cb_ciencias_salud.setEnabled(true);

        }
    }//GEN-LAST:event_rd_cienca_saludActionPerformed

    private void cb_sistemasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_sistemasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_sistemasActionPerformed

    private void jl_estudiantesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_estudiantesMousePressed
        // TODO add your handling code here:
        
        ////
        if(jl_estudiantes.getSelectedIndex() >=0){
        if(evt.isMetaDown()){
            DefaultTreeModel tree_model = (DefaultTreeModel) jTree1.getModel(); 
            DefaultMutableTreeNode model_raiz = (DefaultMutableTreeNode) tree_model.getRoot();
                    //DefaultMutableTreeNode persona_nodo;
                    DefaultListModel lista_model = (DefaultListModel)jl_estudiantes.getModel();
                    String sexo = ""; 
                    if(rb_hombre.isSelected()){
                        sexo = "Hombre"; 
                    }else {
                        sexo = "Mujer"; 
                    }
                    
                     carrera carre = null;
            if (rd_sistema.isSelected()) {
                carre = (carrera) cb_sistemas.getSelectedItem();
            }
            if (rd_licenciatura.isSelected()) {
                carre = (carrera) cb_licenciatura.getSelectedItem();
            }
            if (rd_cienca_salud.isSelected()) {
                carre = (carrera) cb_ciencias_salud.getSelectedItem();
            }
            
             String nombre = jt_estudiantes.getText();
            String apellido = tf_apellido.getText();
            int edad = (int) sp_edad.getValue();
            int num_cuenta = 34 + ale.nextInt(10000); 
            
            nombre = ((estudiantes)lista_model.get(jl_estudiantes.getSelectedIndex())).getNombre();
            apellido = ((estudiantes)lista_model.get(jl_estudiantes.getSelectedIndex())).getApellido();
            edad = ((estudiantes)lista_model.get(jl_estudiantes.getSelectedIndex())).getEdad();
            num_cuenta = ((estudiantes)lista_model.get(jl_estudiantes.getSelectedIndex())).getNum_cuenta();
            sexo = ((estudiantes)lista_model.get(jl_estudiantes.getSelectedIndex())).getSexo();
            carre = ((estudiantes)lista_model.get(jl_estudiantes.getSelectedIndex())).getCarre();
            int centinela = -1; 
            for (int i = 0; i < model_raiz.getChildCount(); i++) {
                if(model_raiz.getChildAt(i).toString().equals(carre)){
                DefaultMutableTreeNode P = new DefaultMutableTreeNode(new estudiantes(nombre, apellido, num_cuenta, edad, sexo, carre));
                ((DefaultMutableTreeNode) model_raiz.getChildAt(i)).add(P);
                centinela = 1;
                }
            }
            if(centinela == -1){
            DefaultMutableTreeNode n = new DefaultMutableTreeNode(carre);
            DefaultMutableTreeNode p = new DefaultMutableTreeNode(new estudiantes(nombre, apellido, num_cuenta, edad, sexo, carre));
            n.add(p);
            model_raiz.add(n);
            }
            tree_model.reload();
        }
            
//
////            persona_nodo = new DefaultMutableTreeNode(new estudiantes(jt_estudiantes.getText(), tf_apellido.getText(), ale.nextInt(3), (Integer) sp_edad.getValue(), sexo, carre));
////            DefaultMutableTreeNode carrera_nodo = new DefaultMutableTreeNode(carre);
//
//            carrera_nodo.add(persona_nodo);
//            model_raiz.add(carrera_nodo);
//            tree_model.reload();

        }
    }//GEN-LAST:event_jl_estudiantesMousePressed

    private void jTree1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MousePressed
        // TODO add your handling code here:
       if(evt.isMetaDown()){
       
           if (evt.isMetaDown()) {
               // aca capturamos la fila mas cercana a donde se hace click 
               int row = jTree1.getClosestRowForLocation(evt.getX(), evt.getY());
               // aca la dejamos como fila seleccionada
               jTree1.setSelectionRow(row);
               // sacamos el objeto 
               Object obj = jTree1.getSelectionPath().getLastPathComponent();
               // agarramos el nodo seleccionado que es el objeto 
               nodo_seleccionado = (DefaultMutableTreeNode) obj;
               // se valida que hayan clientes en el nodo 
               if (nodo_seleccionado.getUserObject() instanceof carrera) {
                   cliente_seleccionado = (carrera) nodo_seleccionado.getUserObject(); // se pasa a la variable que es persona 
                   Eliminar_modificar.show(evt.getComponent(), evt.getX(), evt.getY()); // se muestra el menu 
               }

           }

        }
    }//GEN-LAST:event_jTree1MousePressed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
        int delete = JOptionPane.showConfirmDialog(this, "Seguro de eliminar? ", "Confirm", JOptionPane.YES_OPTION, JOptionPane.QUESTION_MESSAGE); // se manda el mensaje 
        if (delete == JOptionPane.OK_OPTION) { // se confirma la opcion 
            DefaultTreeModel model = (DefaultTreeModel) jTree1.getModel();  // se captura el modelo 
            model.removeNodeFromParent(nodo_seleccionado); // se remueve el modelo 
            model.reload(); // se manda la imagen 
        }


    }//GEN-LAST:event_EliminarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        // TODO add your handling code here:
        DefaultTreeModel model = (DefaultTreeModel) jTree1.getModel();
        cliente_seleccionado.setNombre(JOptionPane.showInputDialog("Ingrese el nuevo nombre: "));
        model.reload();
    }//GEN-LAST:event_ModificarActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        carrer();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void rd_cienciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_cienciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd_cienciaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        try {
            String nombre = jTextField1.getText();
            String facultad = jTextField2.getText();
            float costo_mensual = Float.parseFloat(jFormattedTextField1.getText());
            String jefe_carrera = jTextField3.getText();
            String nombre_carrera = jTextField4.getText();
            if (rd_ing.isSelected()) {
                ing_sistemas siste = new ing_sistemas(nombre_carrera, nombre, facultad, costo_mensual, jefe_carrera);
                DefaultComboBoxModel sis = (DefaultComboBoxModel)cb_sistemas.getModel(); 
                sis.addElement(siste);
                cb_sistemas.setModel(sis);

            }
            if (rd_lic.isSelected()) {
                Licencuatura lic = new Licencuatura(nombre_carrera, nombre, facultad, costo_mensual, jefe_carrera);
                DefaultComboBoxModel lic_mo = (DefaultComboBoxModel) cb_licenciatura.getModel();
                lic_mo.addElement(lic);
                cb_licenciatura.setModel(lic_mo);

            }
            if (rd_ciencia.isSelected()) {
                ciencias_salud cin = new ciencias_salud(nombre_carrera, nombre, facultad, costo_mensual, jefe_carrera);
                DefaultComboBoxModel cien = (DefaultComboBoxModel) cb_ciencias_salud.getModel();
                cien.addElement(cin);
                cb_ciencias_salud.setModel(cien);

            }
            JOptionPane.showMessageDialog(this, "Correcto");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        clasee();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        try {
            String nombre = jTextField5.getText();
            int seccion = Integer.parseInt(jFormattedTextField2.getText());
            String edificacion = jTextField6.getText();
            String salon = jTextField7.getText();
            String aire = "";
            if (jRadioButton1.isSelected()) {
                aire = "SI";
            } else {
                aire = "NO";
            }

            clases clas = new clases(nombre, seccion, edificacion, salon, edificacion);

            cla.add(clas);

            DefaultComboBoxModel mo = (DefaultComboBoxModel) cb_class.getModel();
            mo.addElement(clas);
            DefaultListModel mod = (DefaultListModel) jl_maestro_clases.getModel();
            mod.addElement(clas);
            jl_maestro_clases.setModel(mod);

            cb_class.setModel(mo);
            cb_class1.setModel(mo);
            JOptionPane.showMessageDialog(this, "Correcto");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR");
        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        Mastroo();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
if(cla.size()==0){JOptionPane.showMessageDialog(this, "Aun no existen clases para los maestro :( ");} else {
        try {

            String nombre = jTextField8.getText();
            String apellido = jTextField9.getText();
            float salario = Float.parseFloat(jFormattedTextField3.getText());
            int edad = Integer.parseInt(jFormattedTextField4.getText());
            clases cl = (clases) cb_class.getSelectedItem();
            ArrayList<clases> claa = new ArrayList();
            claa.add(cl);

            Maestro ma = new Maestro(nombre, apellido, salario, edad);
            ma.setClase(claa);
            DefaultListModel mod = (DefaultListModel) jl_maestro_clases.getModel();
            mod.addElement(ma);
            jl_maestro_clases.setModel(mod);

            JOptionPane.showMessageDialog(this, "Correcto");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR");

        }
}
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        Lista_ma_c();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jl_maestro_clasesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_maestro_clasesMouseClicked
        // TODO add your handling code here:
        if (jl_maestro_clases.getSelectedIndex() >= 0) { // se verifica este seleccionado algo de la lista 

            if (evt.isMetaDown()) { // esto se hace para que se despliegue el menu opcional dandole click derecho a lo que esta en nuestra lista 
                menu_lista_maestro_clases.show(evt.getComponent(), evt.getX(), evt.getY());  // esto se hace para que se muestre el menu (el padre (el objeto (el jList)), posicion x , posicion y)
            }

        }
    }//GEN-LAST:event_jl_maestro_clasesMouseClicked

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        DefaultListModel model = (DefaultListModel) jl_maestro_clases.getModel(); 
            model.remove(jl_maestro_clases.getSelectedIndex()); 
            jl_maestro_clases.setModel(model);
            JOptionPane.showMessageDialog(this, "Eliminado correctamente");
    }//GEN-LAST:event_DeleteActionPerformed

    private void ModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModActionPerformed
        // TODO add your handling code here:
       try{ if (jl_maestro_clases.getSelectedIndex() >= 0) {
           mod_master();
//            DefaultListModel model = (DefaultListModel) jl_maestro_clases.getModel();
//
//            ((Maestro) model.get(jl_maestro_clases.getSelectedIndex())).setNombre(JOptionPane.showInputDialog("Ingrese el nuevo nombre: "));
//            jl_maestro_clases.setModel(model);
        }
       }
       catch(Exception e){
           JOptionPane.showMessageDialog(this, "Error");
       }
    }//GEN-LAST:event_ModActionPerformed

    private void Mod_clasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mod_clasesActionPerformed
        // TODO add your handling code here:
try{
    
    mod_clases();
    
//        if (jl_maestro_clases.getSelectedIndex() >= 0) {
//            DefaultListModel model = (DefaultListModel) jl_maestro_clases.getModel();
//                ((clases) model.get(jl_maestro_clases.getSelectedIndex())).setNombre(JOptionPane.showInputDialog("Ingrese el nuevo nombre: "));
//                jl_maestro_clases.setModel(model);
//            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error");
        }
    }//GEN-LAST:event_Mod_clasesActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        // TODO add your handling code here:
        
        try{
        if (jl_maestro_clases.getSelectedIndex() >= 0) {
            
            
            String nombre = jTextField10.getText();
            String aire = ""; 
            if(jRadioButton3.isSelected()){
                aire = "si";
            } else {
                aire = "no";
            }
            DefaultListModel model = (DefaultListModel) jl_maestro_clases.getModel();
            ((clases) model.get(jl_maestro_clases.getSelectedIndex())).setNombre(nombre);
            ((clases) model.get(jl_maestro_clases.getSelectedIndex())).setSeccion(Integer.parseInt(jFormattedTextField5.getText()));
            ((clases) model.get(jl_maestro_clases.getSelectedIndex())).setEdificio(jTextField11.getText());
            ((clases) model.get(jl_maestro_clases.getSelectedIndex())).setSalon(jTextField12.getText());
            ((clases) model.get(jl_maestro_clases.getSelectedIndex())).setAire_codicionado(aire);
            jl_maestro_clases.setModel(model);
            JOptionPane.showMessageDialog(this, "Correcto");
        } 
        }
        
        catch(Exception e){
                       JOptionPane.showMessageDialog(this, "Error");

        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try {
            if (jl_maestro_clases.getSelectedIndex() >= 0) {
                
                mod_master();
                DefaultListModel model = (DefaultListModel) jl_maestro_clases.getModel();
                String nombre = jTextField13.getText();
                ((Maestro) model.get(jl_maestro_clases.getSelectedIndex())).setNombre(nombre);
                ((Maestro) model.get(jl_maestro_clases.getSelectedIndex())).setApellido(jTextField14.getText());
                ((Maestro) model.get(jl_maestro_clases.getSelectedIndex())).setSalario(Float.parseFloat(jFormattedTextField6.getText()));
                ((Maestro) model.get(jl_maestro_clases.getSelectedIndex())).setEdad(Integer.parseInt(jFormattedTextField7.getText()));
                clases s = (clases) cb_class1.getSelectedItem();
                ArrayList<clases> clax = new ArrayList();                
                clax.add(s);                
                ((Maestro) model.get(jl_maestro_clases.getSelectedIndex())).setClase(clax);
                
                jl_maestro_clases.setModel(model);
            }
        }
       catch(Exception e){
           JOptionPane.showMessageDialog(this, "Error");
       }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    
    
    public void estudiante(){
         estudian.pack();
        estudian.setModal(true);
        estudian.setLocationRelativeTo(this);
        estudian.setVisible(true);
    }
     public void carrer(){
         Carreras.pack();
        Carreras.setModal(true);
        Carreras.setLocationRelativeTo(this);
        Carreras.setVisible(true);
    }

    public void clasee() {
        Clases.pack();
        Clases.setModal(true);
        Clases.setLocationRelativeTo(this);
        Clases.setVisible(true);
    }

    public void Mastroo() {
        Maestro.pack();
        Maestro.setModal(true);
        Maestro.setLocationRelativeTo(this);
        Maestro.setVisible(true);
    }

    public void Lista_ma_c() {
        lista_maestro_clase.pack();
        lista_maestro_clase.setModal(true);
        lista_maestro_clase.setLocationRelativeTo(this);
        lista_maestro_clase.setVisible(true);
    }
  public void mod_clases() {
        Modificar_clases.pack();
        Modificar_clases.setModal(true);
        Modificar_clases.setLocationRelativeTo(this);
        Modificar_clases.setVisible(true);
    }
  
          public void mod_master() {
        Modificar_Maestro.pack();
        Modificar_Maestro.setModal(true);
        Modificar_Maestro.setLocationRelativeTo(this);
        Modificar_Maestro.setVisible(true);
    }

    DefaultMutableTreeNode nodo_seleccionado; 
    carrera cliente_seleccionado; 
    ArrayList <clases> cla = new ArrayList(); 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Carreras;
    private javax.swing.JDialog Clases;
    private javax.swing.JMenuItem Delete;
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JPopupMenu Eliminar_modificar;
    private javax.swing.JDialog Maestro;
    private javax.swing.JMenuItem Mod;
    private javax.swing.JMenuItem Mod_clases;
    private javax.swing.JMenuItem Modificar;
    private javax.swing.JDialog Modificar_Maestro;
    private javax.swing.JDialog Modificar_clases;
    private javax.swing.ButtonGroup aire;
    private javax.swing.ButtonGroup carreras;
    private javax.swing.JComboBox<String> cb_ciencias_salud;
    private javax.swing.JComboBox<String> cb_class;
    private javax.swing.JComboBox<String> cb_class1;
    private javax.swing.JComboBox<String> cb_licenciatura;
    private javax.swing.JComboBox<String> cb_sistemas;
    private javax.swing.JDialog estudian;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JFormattedTextField jFormattedTextField5;
    private javax.swing.JFormattedTextField jFormattedTextField6;
    private javax.swing.JFormattedTextField jFormattedTextField7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTree jTree1;
    private javax.swing.JList<String> jl_estudiantes;
    private javax.swing.JList<String> jl_maestro_clases;
    private javax.swing.JTextField jt_estudiantes;
    private javax.swing.JDialog lista_maestro_clase;
    private javax.swing.JPopupMenu menu_lista_maestro_clases;
    private javax.swing.JRadioButton rb_hombre;
    private javax.swing.JRadioButton rd_cienca_salud;
    private javax.swing.JRadioButton rd_ciencia;
    private javax.swing.JRadioButton rd_ing;
    private javax.swing.JRadioButton rd_lic;
    private javax.swing.JRadioButton rd_licenciatura;
    private javax.swing.JRadioButton rd_mujer;
    private javax.swing.JRadioButton rd_sistema;
    private javax.swing.ButtonGroup sexos;
    private javax.swing.JSpinner sp_edad;
    private javax.swing.JTextField tf_apellido;
    // End of variables declaration//GEN-END:variables
}
